added swift and modularized entire set. Also broke out util scripts for easy re-use

diff --git a/utils/openstack-keystone-setup b/utils/openstack-keystone-setup
--- a/utils/openstack-keystone-setup
+++ b/utils/openstack-keystone-setup
@@ -9,39 +9,12 @@ if [ -n "$DB_ROOT_PW" ]; then
  DBPW="--rootpw $DB_ROOT_PW"
 fi
 
-set_bootstrap_auth(){
-    export SERVICE_ENDPOINT
-    export SERVICE_TOKEN
-    export -n OS_AUTH_URL
-    export -n OS_PASSWORD
-    export -n OS_USERNAME
-    export -n OS_REGION_NAME
-    export -n OS_TENANT_NAME
-}
-
-set_standard_auth(){
-    export -n SERVICE_ENDPOINT
-    export -n SERVICE_TOKEN
-    export OS_AUTH_URL
-    export OS_PASSWORD
-    export OS_USERNAME
-    export OS_REGION_NAME
-    export OS_TENANT_NAME
-}
-
-save_runtime(){
-    OUTFILE=$1
-    {
-     echo "export OS_AUTH_URL=${OS_AUTH_URL}"
-     echo "export OS_PASSWORD=${OS_PASSWORD}"
-     echo "export OS_USERNAME=${OS_USERNAME}"
-     echo "export OS_REGION_NAME=${OS_REGION_NAME}"
-     echo "export OS_TENANT_NAME=${OS_TENANT_NAME}"
-     echo "OS_SERVICE_ENDPOINT=${OS_SERVICE_ENDPOINT}"
-     echo "OS_SERVICE_TOKEN=${OS_SERVICE_TOKEN}"
-     echo "OS_IDENTITY_API_VERSION=2.0"
-    } > $OUTFILE
-}
+if [ -e "${SETUP_UTILS}" ]; then
+    . ${SETUP_UTILS}
+else
+    echo "Setup Utils file: $SETUP_UTILS is missing"
+    exit 1
+fi
 
 openstack-db -y --init --service keystone $DBPW
 
