getting things more organized

diff --git a/utils/openstack-keystone-setup b/utils/openstack-keystone-setup
--- a/utils/openstack-keystone-setup
+++ b/utils/openstack-keystone-setup
@@ -1,9 +1,13 @@
 #!/bin/sh
-RCFILE=openstack-setup.rc
+RCFILE=${1:-"openstack-setup.rc"}
 
 if [ -e ${RCFILE} ]; then
  . $RCFILE
+else
+ echo "Missing ${RCFILE}"
+ exit 1
 fi
+
 
 if [ -n "$DB_ROOT_PW" ]; then
  DBPW="--rootpw $DB_ROOT_PW"
diff --git a/utils/openstack-keystone-setup-data b/utils/openstack-keystone-setup-data
--- a/utils/openstack-keystone-setup-data
+++ b/utils/openstack-keystone-setup-data
@@ -65,10 +65,14 @@ MY_REGION=${MY_REGION:-RegionOne}
 # $MY_PUB_TENANT       $MY_USER  Member,sysadmin,netadmin
 # $MY_PRIV_TENANT      $MY_USER  Member
 
-RCFILE=${SETUP_RC:-"openstack-setup.rc"}
+
+RCFILE=${1:-"openstack-setup.rc"}
 
 if [ -e ${RCFILE} ]; then
  . $RCFILE
+else
+ echo "Missing ${RCFILE}"
+ exit 1
 fi
 
 if [ -n "$DB_ROOT_PW" ]; then
diff --git a/utils/openstack-setup b/utils/openstack-setup
--- a/utils/openstack-setup
+++ b/utils/openstack-setup
@@ -1,23 +1,18 @@
 #!/bin/sh
 
-RCFILE=openstack-setup.rc
+RCFILE=${1:-"openstack-setup.rc"}
 
 if [ -e ${RCFILE} ] ; then
  . $RCFILE
-fi
-
-if [ -e "$SETUP_UTILS" ] ; then
-    . ${SETUP_UTILS}
 else
-    echo "Missing Setup Utils"
+ echo "Missing $RCFILE"
+ exit 1
 fi
 
+[ -n "$ENABLE_KEYSTONE" ]   && openstack-keystone-setup $RCFILE
+[ -n "$ENABLE_GLANCE" ]     && openstack-glance-setup   $RCFILE
+[ -n "$ENABLE_NOVA" ]       && openstack-nova-setup     $RCFILE
+[ -n "$ENABLE_CINDER" ]     && openstack-cinder-setup   $RCFILE
+[ -n "$ENABLE_HORIZON" ]    && openstack-horizon-setup  $RCFILE
+[ -n "$ENABLE_SWIFT" ]      && openstack-swift-setup    $RCFILE
 
-openstack-keystone-setup
-openstack-glance-setup
-openstack-nova-setup
-openstack-cinder-setup
-openstack-horizon-setup
-openstack-swift-setup
-
-save_runtime $RUNTIME_RC
